title: TOPE
description: Trinity Open Psychological Experiments
theme: just-the-docs

url: https://mklab-japan.github.io/tope

aux_links:
  GitHub: https://github.com/mklab-japan/tope

color_scheme: tope

nav_enabled: true

callouts:
  memo:
    title: "ğŸ“ãƒ¡ãƒ¢"
    color: blue
  warning:
    title: "âš æ³¨æ„"
    color: red
  point:
    title: "ğŸ’¡ãƒã‚¤ãƒ³ãƒˆ"
    color: yellow