title: TOPE
description: Trinity Open Psychological Experiments
theme: just-the-docs

logo: "/data/logo.png"

url: https://mklab-japan.github.io/tope

aux_links:
  GitHub: https://github.com/mklab-japan/tope

color_scheme: tope

nav_enabled: true

callouts:
  memo:
    titile: ğŸ“ãƒ¡ãƒ¢
    color: blue
  warning:
    titile: âš æ³¨æ„
    color: red
  points:
    titile: ğŸ’¡ãƒã‚¤ãƒ³ãƒˆ
    color: yellow